ce\models\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
    password:
      type: string
    mail:
      type: string
    type:
      type: string
  oneToMany:
    posts:
      targetEntity: ce\models\Post
      mappedBy: user